local-phone-apps = BackupRestoreConfirmation \
                   BadgeProvider \
                   BluetoothAvrcp \
                   BluetoothMap \
                   BluetoothTest \
                   CSC \
                   ClipboardSaveService \
                   DefaultContainerService \
                   Divx \
                   EdmVpnServices \
                   FaceLock \
                   FactoryTest \
                   FmRadio \
                   GoogleFeedback \
                   GoogleTTS \
                   KeyChain \
                   LogsProvider \
                   MediaUploader \
                   MusicFX \
                   OmaCP \
                   PCWClientS \
                   PRUI \
                   PanningTryActually \
                   Personalization \
                   PhoneErrService \
                   PopupuiReceiver \
                   Preconfig \
                   PreloadInstaller \
                   SamsungTTS \
				   SamsungCamera \
				   SecBluetooth \
				   BluetoothAvrcp \
				   BluetoothMap \
				   BluetoothTest \
                   SecBrowser \
				   SecHTMLViewer \
                   SecOmaDownloadProvider \
				   SecLiveWallpapersPicker \
				   SecWallpaperChooser \
				   SecMediaProvider \
                   SecPhone \
                   SecurityProvider \
                   SelfTestMode \
                   ShareApp \
                   SharedStorageBackup \
                   Stk \
                   Street \
                   UserDictionaryProvider \
                   VpnDialogs \
                   WAPPushManager \
                   WlanTest \
                   minimode-res \
                   serviceModeApp \
                   wssyncmlnps \
                   ApplicationsProvider \
				   SMemo \
				   SMemoProvider
